declare module 'vue-tiny-slider'
declare module 'glightbox'
declare module 'vue3-apexcharts'
declare module '@splidejs/vue-splide'
declare module 'imagesloaded'
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.png';
declare module '*.svg';
declare module '*.json';
